backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "settings"
    label: "إعدادات الموقع"
    files:
      - file: "index.html"
        label: "الصفحة الرئيسية"
        name: "homepage"
        fields:
          - { label: "رقم الهاتف", name: "phone_number", widget: "string" }
          - { label: "عنوان العمل", name: "address", widget: "string" }

